#Help command
helpCommand:
  - '&b[Bang] Help:'
  - '&b/bang banchat&f <player> - make a player cant chat'
  - '&b/bang dead&f <player> - add a player to dead list'
  - '&b/bang fuck&f <player> - add a player mother to cemetery'
  - '&b/bang magic&f <player> - add a player to magic list'
  - '&b/bang bless&f <player> - bless a player with 7 god bless'
  - '&b/bang supajp&f <player> - 3 times speed'
  - '&b/bang uglyface&f <player> - show elder guardian ugly face and warning message'
  - '&b/bang teleport <player>|<x,z,y>|<player1> [player2]|<player> <x,z,y>'
  - '&b/bang freeze&f <player> - freeze a player, cant move'
  - '&b/bang back&f <fuck|magic|bless|supajp|all> <player> - clear all bang effect'
  - '&b/bang list&f - lists the mother fucker players'
  - '&b/bang reload&f - reload bang config file'
  - '&b/bang help&f - shows this help'
warningMsg: ""
info:
  command:
    banchat: '&b/bang banchat&f <player>'
    dead: '&b/bang dead&f <player>'
    fuck: '&b/bang fuck&f <player>'
    magic: '&b/bang magic&f <player>'
    bless: '&b/bang bless&f <player>'
    supajp: '&b/bang supajp'
    uglyface: '&b/bang uglyface <player>'
    teleport: '&b/bang teleport <player>|<x,z,y>|<player1> [player2]|<player> <x,z,y>'
    freeze: '&b/bang freeze <player>'
    back: '&b/bang back&f <fuck|magic|bless|supajp|freeze|all> <player>'
    list: '&b/bang list'
    reload: '&b/bang reload'
    help: '&b/bang help'
  add:
    success: 'Add success!'
    contained: 'Player is contained'
  remove:
    success: 'Remove success!'
    no-online: 'Player has been removed, and relevant effect will be removed when next online'
    no-player: 'Player not in list'
  player:
    no-player: 'The player has never existed on the server'
    no-found: 'Player not found'
  reload:
    success: 'Reload success!'
  uglyface:
    success: 'Success!'
  permission:
    no: 'No permission!'
