#Help command
helpCommand:
  - '&b[Bang] Help:'
  - '&b/bang banchat&e <player>&f - 禁言'
  - '&b/bang dead&e <player>&f - 反复处死一名玩家'
  - '&b/bang fuck&e <player>&f - 尝试崩端'
  - '&b/bang magic&e <player>&f - 添加负面效果'
  - '&b/bang supajp&e <player>&f - 苏帕~酱噗!'
  - '&b/bang uglyface&e <player>&f - 播放守护者动画和音乐效果'
  - '&b/bang teleport&f - 传送指令, 使用&b/bang teleport&f查看更多说明'
  - '&b/bang freeze&e <player>&f - 冰魔法·封绝 冻结一名玩家'
  - '&b/bang observe&f - 在生存模式与观察者模式之间来回切换'
  - '&b/bang back&e <fuck|magic|bless|supajp|all> <player>&f - 移除玩家身上的某种效果'
  - '&b/bang list&f - 列出作用的玩家名单'
  - '&b/bang reload&f - 重载配置文件'
  - '&b/bang help&f - 显示帮助'
warningMsg: ""
info:
  command:
    banchat: '&b[Bang] /bang banchat&e <player>'
    dead: '&b[Bang] /bang dead&e <player>'
    fuck: '&b[Bang] /bang fuck&e <player>'
    magic: '&b[Bang] /bang magic&e <player>'
    bless: '&b[Bang] /bang bless&e <player>'
    supajp: '&b[Bang] /bang supajp'
    uglyface: '&b[Bang] /bang uglyface&e <player>'
    teleport: '&b[Bang] /bang teleport&e <player>;&b[Bang] /bang teleport&e <playerA> <playerB>
    ;&b[Bang] /bang teleport&e x y z;&b[Bang] /bang teleport&e <player> x y z'
    freeze: '&b[Bang] /bang freeze&e <player>'
    observe: '&b[Bang] /bang observe'
    back: '&b[Bang] /bang back&e <fuck|magic|bless|supajp|freeze|all> <player>'
    list: '&b[Bang] /bang list'
    reload: '&b[Bang] /bang reload'
    help: '&b[Bang] /bang help'
  add:
    success: '&a[Bang] 添加成功!'
    contained: '&c[Bang] 玩家已经在列表中了'
  remove:
    success: '&a[Bang] 移除成功'
    no-online: '&a[Bang] 已在列表中移除该玩家, 附加状态将在下次其登录后解除'
    no-player: '&c[Bang] 玩家不在该列表中'
  observe:
    survival: '&a[Bang] 冰魔法的力量消失了...'
    spectator: '&a[Bang] 念诵起了冰魔法的咒语, 随后悄然融入了天地之间'
    wrong: '&c[Bang] 似乎受到了一些神秘力量的阻碍(仅在生存或观察者模式时才能使用)'
  player:
    no-player: '&c[Bang] 服务器中没有该玩家的相关信息'
    no-found: '&c[Bang] 玩家不存在'
  reload:
    success: '&a[Bang] 重载成功!'
  uglyface:
    success: '&a[Bang] 施放成功!'
  permission:
    no: '&4[Bang] 没有权限!'
