name: Bang
version: 3.1.5
main: org.gbcraft.bang.Bang
api-version: 1.16
depend: [ProtocolLib]
authors: [IceBlues7]
description: Fucking mother fucker boys

commands:
  bang:
    description: Bang! ovo!
    permission: bang.base

