name: Bang
version: 2.0.9
main: org.gbcraft.bang.Bang
api-version: 1.13
depend: [ProtocolLib]
authors: [IceBlues7]
description: Fucking mother fucker boys

commands:
  bang:
    description: Bang! ovo!
    permission: bang.base

